mode: gl

camera:
  id: 0
  width: 1280
  height: 720
  fps: 30

images:
  paths: ["calligraphy_interactive/assets/calligraphy.png"]
  cycle_seconds: 20

effects:
  gl:
    window:
      width: 1280
      height: 720
      fullscreen: false
    ink:
      strength_scale: 2.5
      noise_amount: 0.6

logging:
  level: INFO

osc:
  enabled: true
  host: "127.0.0.1"
  port: 9000

debug:
  enabled: true
  draw_landmarks: true
  draw_velocity: true
  draw_text: true
  show_fps: true
  draw_thumb_index_line: true

gesture:
  hand_reference_size_cm: 18.0  # 손바닥 대각선 평균 크기 (cm)


